### ISSUE TITLE
Masalah testing RefreshDatabase untuk migration AddRoleIdOnUser

### ISSUE THREAD

**Issue by rizkyarlin** [relawancovid19/lab-information#16]
Pada PR #15 sy membuat tampilan dashboard. Saya mulai membuat test untuk itu, sayangnya pada saat penggunaan `RefreshDatabase`, migration `AddRoleIdOnUser` terdapat baris `$table->bigInteger('role_id', false, true);` yang menambah filed role_id tanpa default value ataupun nullable. Untuk driver mysql, ini aman2 sj, tp untuk testing driver sqlite menjadi masalah.

Ada 2 solusi untuk masalah ini:
1. phpunit.xml nya kt ubah drivernya
2. role_id diberi default value
3.  role_id dibuat nullable

**Comment by andisis** [comment]
Halo mas @rizkyarlin , makasih buat antusiasnya
project ini butuh cepet jadi kita ga utamain testing, kalo mau ada yang bikin testing bisa gunakan Mockery untuk mock datanya, jadi ga perlu DB

**Comment by rizkyarlin** [comment]
berarti readme-nya harus diupdate mas @andisis

**Comment by rizkyarlin** [comment]
Readme:
>Note :

>Please make sure to update tests as appropriate.
>It's recommended to run Testing command before submit a pull request.

**Comment by andisis** [comment]
makasih banyak mas @rizkyarlin koreksinya
saya udah update readmenya di PR saya
